class DominosTester{
	
	public static void main(String foodDelivery[]){
		
		String foodName = "Blazing onion";
		double quantity = 2;
		double foodPrice = Dominos.search(foodName  , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice);
		String foodName1 = "Paneer with sauce";
		quantity = 2;
		double foodPrice1 = Dominos.search(foodName1  , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice1);
		String foodName2 = "Non veg loaded";
		quantity = 2;
		double foodPrice2 = Dominos.search(foodName2  , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice2);
		String foodName3 = "Pepper Barbecue Chicken";
		quantity = 2;
		double foodPrice3 = Dominos.search(foodName3 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice3);
		String foodName4 = "Veg loaded";
		quantity = 2;
		double foodPrice4 = Dominos.search(foodName4 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice4);
		String foodName5 = "Paneer and Capsicum";
		quantity = 2;
		double foodPrice5 = Dominos.search(foodName5 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice5);
		String foodName6 = "Chicken Sausage";
		quantity = 2;
		double foodPrice6 = Dominos.search(foodName6 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice6);
		String foodName7 = "Tomato";
		quantity = 2;
		double foodPrice7 = Dominos.search(foodName7 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice7);
		String foodName8 = "Classic";
		quantity = 2;
		double foodPrice8 = Dominos.search(foodName8 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice8);
		String foodName9 = "Golden Corn";
		quantity = 2;
		double foodPrice9 = Dominos.search(foodName9 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice9);
		String foodName10 = "Onion";
		quantity = 2;
		double foodPrice10 = Dominos.search(foodName10 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice10);
		String foodName11 = "Choco Lava Cake";
		quantity = 2;
		double foodPrice11 = Dominos.search(foodName11 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice11);
		String foodName12 = "Red Velvet Lava Cake";
		quantity = 2;
		double foodPrice12 = Dominos.search(foodName12 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice12);
		String foodName13 = "Butterscotch MOuse Cake";
		quantity = 2;
		double foodPrice13 = Dominos.search(foodName13 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice13);
		String foodName14 = "Fiery Jalapeno";
		quantity = 2;
		double foodPrice14 = Dominos.search(foodName14 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice14);
		String foodName15 = "Primavera Gourmet";
		quantity = 2;
		double foodPrice15 = Dominos.search(foodName15 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice15);
		String foodName16 = "AI Fungi Gourmet Pizza";
		quantity = 2;
		double foodPrice16 = Dominos.search(foodName16 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice16);
		String foodName17 = "Smoked Chicken";
		quantity = 2;
		double foodPrice17 = Dominos.search(foodName17 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice17);
		String foodName18 = "Chicken Salami Gourmet";
		quantity = 2;
		double foodPrice18 = Dominos.search(foodName18 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice18);
		String foodName19 = "Corn And Cheese";
		quantity = 2;
		double foodPrice19 = Dominos.search(foodName19 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice19);
		String foodName20 = "Chicken Keema Parota";
		quantity = 2;
		double foodPrice20 = Dominos.search(foodName20 , quantity);
		System.out.println("the price of the searched food is : "+ foodPrice20);
		quantity = 2;
	}
}